pool:
  vmImage: ubuntu-22.04

trigger:
- main

steps:
- task: Bash@3
  displayName: 'Create seed provider containers'
  inputs:
    targetType: 'inline'
    script: 'docker compose up --detach'
  env:
    PACKAGE_FEED_URL: $(PackageFeedUrl)
    PACKAGE_FEED_PAT: $(PackageFeedPAT)

- task: Bash@3
  displayName: 'Wait for seed provider container to close'
  inputs:
    targetType: 'inline'
    script: 'docker wait rpa-mit-reference-seed-provider'

- task: Bash@3
  displayName: 'Extract SQL dumps'
  inputs:
    targetType: 'inline'
    script: 'docker-compose exec -T rpa-mit-reference-data-postgres sh /home/postgres/extract-seed-data.sh'

- task: Bash@3
  displayName: 'Clean up'
  inputs:
    targetType: 'inline'
    script: 'docker compose down'
  env:
    PACKAGE_FEED_URL: $(PackageFeedUrl)
    PACKAGE_FEED_PAT: $(PackageFeedPAT)

- task: PublishBuildArtifacts@1
  displayName: 'Publish SQL Scripts'
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/seed-data-scripts'
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifactName: sql